import { boolean, integer, numeric, pgTable, serial, text, timestamp, varchar } from "drizzle-orm/pg-core";

export const AmazonMarketProductsModel = pgTable("tbl_amazon_market_products", {
    productId: serial("product_id").primaryKey(),
    amazonCategory: varchar("amazon_category"),
    amazonCategoryUrl: varchar("amazon_category_url"),
    amazonStaticCategoryUrl: varchar("amazon_static_category_url"),
    amazonSubCategory: varchar("amazon_sub_category"),
    amazonSubCategoryUrl: varchar("amazon_sub_category_url"),
    amazonStaticSubCategoryUrl: varchar("amazon_static_sub_category_url"),
    amazonAsinSku: varchar("amazon_asin_sku").notNull(),
    amazonProductUrl: varchar("amazon_product_url"),
    amazonStaticProductUrl: varchar("amazon_static_product_url"),
    amazonProductName: varchar("amazon_product_name"),
    amazonModelNo: varchar("amazon_model_no"),
    amazonProductDescription: text("amazon_product_description"),
    amazonMrp: numeric("amazon_mrp", { precision: 18, scale: 2 }).notNull().default("0.00"),
    amazonInventoryCount: integer("amazon_inventory_count").notNull().default(0),
    amazonCspPrice: numeric("amazon_csp_price", { precision: 18, scale: 2 }).notNull().default("0.00"),
    amazonDiscountedPrice: numeric("amazon_discounted_price", { precision: 18, scale: 2 }).notNull().default("0.00"),
    amazonPoints: numeric("amazon_points", { precision: 18, scale: 2 }).notNull().default("0.00"),
    amazonDiff: numeric("amazon_diff", { precision: 18, scale: 2 }).notNull().default("0.00"),
    amazonUrl: text("amazon_url"),
    amazonCommentsVendor: text("amazon_comments_vendor"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: integer("created_by").notNull(),
    updatedBy: varchar("updated_by").notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
